data:
  input_file : 'test_assets/IRIS_DATA.csv'
  delimiter : ','



save_data: false
experiment_name: 'RF_CICD_PIPELINE'


ModelAssets:
  dir: 'model_assets'
  common_dir : 'model_assets/start_time'


ModelParametrs:
  n_estimators: 100
  max_depth: 10
  random_state: 42
