# .github/workflows/rf_train_pipeline.yml
name: RF_train_Pipeline

on:
  # push:
  #   branches:
  #     - test_v0.1
  workflow_run:
    workflows: ["RF_data_process_Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training
      run: |
        python3 main.py

    # Uncomment if you have tests and want to run them
    # - name: Run tests
    #   run: |
    #     pytest tests/
